version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "yarn.lock" }}
          - dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - ~/.cache
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn ci

workflows:
  version: 2
  workflow_name:
    jobs:
      - build
